# Default configuration for glrdb
# To create this file, run: glrdb init > glrdb.toml

[global]
#db_name = "glrdb.db"
#max_depth = 64
exclude = ["node_modules", "vendor"]

[[sources]]
path = "./"
#exclude = []
