version: 3

env:
  APP_NAME: "glrdb"
  BIN_DIR: "bin"
  BIN_PATH: "{{.BIN_DIR}}/{{.APP_NAME}}"
  DB_NAME: "{{.APP_NAME}}.boltdb"

tasks:
  build:
    desc: "Build"
    sources:
      - ./*.go
    generates:
      - "{{.BIN_PATH}}"
    cmds:
      - mkdir -p {{.BIN_DIR}}
      - go build -o {{.BIN_PATH}} .

  update:
    desc: "DBを更新する"
    deps:
      - build
    cmds:
      - "{{.BIN_PATH}} update"

  print:
    desc: "DBの内容をfzf向けで表示する"
    deps:
      - build
    cmds:
      - "{{.BIN_PATH}} print | fzf --delimiter '\t' --with-nth 1 --preview 'echo {2} | base64 -d' | cut -f1"

  list:
    desc: "DBの内容をサマリで表示する"
    deps:
      - build
    cmds:
      - "{{.BIN_PATH}} list"
  
  init:
    desc: "tomlファイルの初期値を生成する"
    deps:
      - build
    cmds:
      - "{{.BIN_PATH}} init"

  help:
    desc: "ヘルプを表示する"
    deps:
      - build
    cmds:
      - "{{.BIN_PATH}} help"

  clean:
    desc: "Clean"
    cmds:
      - "rm -rf {{.BIN_PATH}} {{.DB_NAME}}"

  tag:
    desc: "タグを更新する"
    deps:
      - build
    cmds:
      - git tag $(./{{.BIN_PATH}} version)
      - git tag

  default:
    cmds:
      - task --list

